syntax on
set nocompatible              
set noswapfile
set backspace=indent,eol,start  
set relativenumber
set hlsearch                  
set incsearch                 
set ignorecase                
set smartcase                 
set tabstop=2                 
set shiftwidth=2              
set expandtab                 
set autoindent                
set linebreak                 
